FROM            eb-docker:base
MAINTAINER      dev@lhy.kr

ENV             BUILD_MODE              local
ENV             DJANGO_SETTINGS_MODULE  config.settings.${BUILD_MODE}

COPY            .   /srv/project
